# Generated by Django 5.2.14 on 2026-05-18 13:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('pickup', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('dropoff', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('package_description', models.CharField(max_length=255)),
                ('package_weight_kg', models.FloatField()),
                ('package_fragile', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0.0)),
                ('price_usd', models.FloatField(default=0.0)),
                ('route', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='drivers.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
