# Generated by Django 5.2.14 on 2026-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="dropoff_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="delivery",
            name="pickup_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
