# Generated by Django 5.2.14 on 2026-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("driver", "Driver"),
                    ("customer", "Customer"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
